/**
 * Prebuilt Tbilisi street crosswalk between myhome.ge and ss.ge spellings.
 *
 * The crosswalk JSON is generated by `scripts/build-street-crosswalk.ts`
 * (`npm run streets:build`) from each site's official street lists. At runtime
 * we normalize an incoming street name and look up the spelling the target
 * site's autocomplete expects, so the same physical street resolves on both
 * platforms regardless of which site it was parsed from.
 */

import crosswalkData from "@/data/tbilisi-street-crosswalk.json";

export type StreetCrosswalkConfidence = "exact" | "fuzzy" | "manual";

export interface StreetCrosswalkEntry {
  myhome: string;
  ssge: string;
  /** District label (myhome `district_name` / ss.ge district title) for disambiguation. */
  district?: string;
  confidence?: StreetCrosswalkConfidence;
}

export type StreetTarget = "myhome" | "ssge";

const crosswalk = crosswalkData as StreetCrosswalkEntry[];

/** Street-type abbreviations → canonical full Georgian word. */
const STREET_TYPE_CANONICAL: Record<string, string> = {
  ქ: "ქუჩა",
  ქუჩა: "ქუჩა",
  გამზ: "გამზირი",
  გამზირი: "გამზირი",
  შეს: "შესახვევი",
  შესახვევი: "შესახვევი",
  ჩიხ: "ჩიხი",
  ჩიხი: "ჩიხი",
  გზტკ: "გზატკეცილი",
  გზატკ: "გზატკეცილი",
  გზატკეცილი: "გზატკეცილი",
  მოედ: "მოედანი",
  მოედანი: "მოედანი",
  დას: "დასახლება",
  დასახლება: "დასახლება",
  ხეივ: "ხეივანი",
  ხეივანი: "ხეივანი",
  აღმ: "აღმართი",
  აღმართი: "აღმართი",
  დაღმ: "დაღმართი",
  დაღმართი: "დაღმართი",
  სანაპ: "სანაპირო",
  სანაპირო: "სანაპირო",
  ჩიქ: "ჩიხი",
};

/**
 * Spelling/transliteration variants collapsed to one canonical stem. Applied as
 * substring replacements so inflected forms (e.g. „აბრაჰამის") collapse too.
 */
const STREET_SPELLING_VARIANTS: [RegExp, string][] = [
  [/კათალიკოს/g, "კათოლიკოს"],
  [/აბრაჰამ/g, "აბრამ"],
];

function nfc(value: string): string {
  return typeof value.normalize === "function" ? value.normalize("NFC") : value;
}

/**
 * Reduce a street name to a comparable key: lower-cased, punctuation/hyphen
 * flattened, street-type abbreviations expanded, trailing house numbers and
 * parentheticals removed, and known spelling variants collapsed.
 */
export function normalizeStreetForMatch(raw: string | null | undefined): string {
  if (!raw) return "";
  let s = nfc(String(raw)).toLowerCase().trim();
  if (!s) return "";

  s = s.replace(/\([^)]*\)/g, " ");
  s = s.replace(/[#№].*$/u, " ");
  s = s.replace(/[-–—_]+/g, " ");
  s = s.replace(/[.,/\\"'`:;]+/g, " ");
  s = s.replace(/\s+/g, " ").trim();
  if (!s) return "";

  let tokens = s.split(" ");

  // Strip trailing house-number-like tokens (e.g. "12", "2-15", "17ა").
  while (tokens.length > 1 && /^\d/.test(tokens[tokens.length - 1])) {
    tokens.pop();
  }

  tokens = tokens
    .map((t) => STREET_TYPE_CANONICAL[t] ?? t)
    .filter((t) => t.length > 0);

  let joined = tokens.join(" ");
  for (const [re, replacement] of STREET_SPELLING_VARIANTS) {
    joined = joined.replace(re, replacement);
  }
  return joined;
}

/** Drop the leading token (initial or first name) — used for person-named streets. */
export function streetMatchKeyWithoutLead(raw: string | null | undefined): string {
  const norm = normalizeStreetForMatch(raw);
  if (!norm) return "";
  const tokens = norm.split(" ");
  if (tokens.length <= 1) return norm;
  return tokens.slice(1).join(" ");
}

export function normalizeDistrictKey(raw: string | null | undefined): string {
  if (!raw) return "";
  return nfc(String(raw))
    .toLowerCase()
    .replace(/[-–—_.,\s]+/g, "")
    .trim();
}

interface LookupMaps {
  toSsge: Map<string, string>;
  toMyhome: Map<string, string>;
  toSsgeByDistrict: Map<string, string>;
  toMyhomeByDistrict: Map<string, string>;
}

const SEP = "\u0000";

function districtScopedKey(districtKey: string, nameKey: string): string {
  return `${districtKey}${SEP}${nameKey}`;
}

function buildLookupMaps(entries: StreetCrosswalkEntry[]): LookupMaps {
  const toSsge = new Map<string, string>();
  const toMyhome = new Map<string, string>();
  const toSsgeByDistrict = new Map<string, string>();
  const toMyhomeByDistrict = new Map<string, string>();

  // Insert exact matches first so they win key collisions over fuzzy ones
  // (e.g. an initial-vs-full-name pairing that normalizes to the same key).
  const ordered = [...entries].sort((a, b) => {
    const rank = (c?: StreetCrosswalkConfidence) =>
      c === "manual" ? 0 : c === "exact" ? 1 : 2;
    return rank(a.confidence) - rank(b.confidence);
  });

  for (const entry of ordered) {
    const myhome = entry.myhome?.trim();
    const ssge = entry.ssge?.trim();
    if (!myhome || !ssge) continue;

    const myhomeKey = normalizeStreetForMatch(myhome);
    const ssgeKey = normalizeStreetForMatch(ssge);
    const districtKey = normalizeDistrictKey(entry.district);

    // A name in either spelling should resolve to the canonical target spelling.
    if (myhomeKey && !toSsge.has(myhomeKey)) toSsge.set(myhomeKey, ssge);
    if (ssgeKey && !toSsge.has(ssgeKey)) toSsge.set(ssgeKey, ssge);
    if (ssgeKey && !toMyhome.has(ssgeKey)) toMyhome.set(ssgeKey, myhome);
    if (myhomeKey && !toMyhome.has(myhomeKey)) toMyhome.set(myhomeKey, myhome);

    if (districtKey) {
      if (myhomeKey) {
        toSsgeByDistrict.set(districtScopedKey(districtKey, myhomeKey), ssge);
        toMyhomeByDistrict.set(districtScopedKey(districtKey, myhomeKey), myhome);
      }
      if (ssgeKey) {
        toSsgeByDistrict.set(districtScopedKey(districtKey, ssgeKey), ssge);
        toMyhomeByDistrict.set(districtScopedKey(districtKey, ssgeKey), myhome);
      }
    }
  }

  return { toSsge, toMyhome, toSsgeByDistrict, toMyhomeByDistrict };
}

let cachedMaps: LookupMaps | null = null;

function maps(): LookupMaps {
  if (!cachedMaps) cachedMaps = buildLookupMaps(crosswalk);
  return cachedMaps;
}

/**
 * Resolve a street name to the spelling expected by `target`'s autocomplete.
 * Returns the canonical target-site spelling, or null when the street is not
 * in the crosswalk (caller should fall back to fuzzy querying).
 */
export function resolveStreetForTarget(
  name: string | null | undefined,
  target: StreetTarget,
  opts?: { district?: string | null }
): string | null {
  const key = normalizeStreetForMatch(name);
  if (!key) return null;

  const m = maps();
  const districtKey = normalizeDistrictKey(opts?.district);

  if (districtKey) {
    const scoped =
      target === "ssge"
        ? m.toSsgeByDistrict.get(districtScopedKey(districtKey, key))
        : m.toMyhomeByDistrict.get(districtScopedKey(districtKey, key));
    if (scoped) return scoped;
  }

  const flat = target === "ssge" ? m.toSsge.get(key) : m.toMyhome.get(key);
  return flat ?? null;
}

/** Number of crosswalk entries currently loaded (diagnostics/tests). */
export function streetCrosswalkSize(): number {
  return crosswalk.length;
}
