/**
 * Prebuilt Tbilisi street crosswalk between myhome.ge and ss.ge spellings.
 *
 * The crosswalk JSON is generated by `scripts/build-street-crosswalk.ts`
 * (`npm run streets:build`) from each site's official street lists. At runtime
 * we normalize an incoming street name and look up the spelling the target
 * site's autocomplete expects, so the same physical street resolves on both
 * platforms regardless of which site it was parsed from.
 */

import crosswalkData from "@/data/tbilisi-street-crosswalk.json";

export type StreetCrosswalkConfidence = "exact" | "fuzzy" | "manual";

export interface StreetCrosswalkEntry {
  myhome: string;
  ssge: string;
  /** District label (myhome `district_name` / ss.ge district title) for disambiguation. */
  district?: string;
  confidence?: StreetCrosswalkConfidence;
}

export type StreetTarget = "myhome" | "ssge";

const crosswalk = crosswalkData as StreetCrosswalkEntry[];

/** Street-type abbreviations → canonical full Georgian word. */
const STREET_TYPE_CANONICAL: Record<string, string> = {
  ქ: "ქუჩა",
  ქუჩა: "ქუჩა",
  გამზ: "გამზირი",
  გამზირი: "გამზირი",
  შეს: "შესახვევი",
  შესახვევი: "შესახვევი",
  ჩიხ: "ჩიხი",
  ჩიხი: "ჩიხი",
  გზტკ: "გზატკეცილი",
  გზატკ: "გზატკეცილი",
  გზატკეცილი: "გზატკეცილი",
  მოედ: "მოედანი",
  მოედანი: "მოედანი",
  დას: "დასახლება",
  დასახლება: "დასახლება",
  ხეივ: "ხეივანი",
  ხეივანი: "ხეივანი",
  აღმ: "აღმართი",
  აღმართი: "აღმართი",
  დაღმ: "დაღმართი",
  დაღმართი: "დაღმართი",
  სანაპ: "სანაპირო",
  სანაპირო: "სანაპირო",
  ჩიქ: "ჩიხი",
};

/**
 * Spelling/transliteration variants collapsed to one canonical stem. Applied as
 * substring replacements so inflected forms (e.g. „აბრაჰამის") collapse too.
 */
const STREET_SPELLING_VARIANTS: [RegExp, string][] = [
  [/კათალიკოს/g, "კათოლიკოს"],
  [/აბრაჰამ/g, "აბრამ"],
];

function nfc(value: string): string {
  return typeof value.normalize === "function" ? value.normalize("NFC") : value;
}

/**
 * Reduce a street name to a comparable key: lower-cased, punctuation/hyphen
 * flattened, street-type abbreviations expanded, trailing house numbers and
 * parentheticals removed, and known spelling variants collapsed.
 */
export function normalizeStreetForMatch(raw: string | null | undefined): string {
  if (!raw) return "";
  let s = nfc(String(raw)).toLowerCase().trim();
  if (!s) return "";

  s = s.replace(/\([^)]*\)/g, " ");
  s = s.replace(/[#№].*$/u, " ");
  s = s.replace(/[-–—_]+/g, " ");
  s = s.replace(/[.,/\\"'`:;]+/g, " ");
  s = s.replace(/\s+/g, " ").trim();
  if (!s) return "";

  let tokens = s.split(" ");

  // Strip trailing house-number-like tokens (e.g. "12", "2-15", "17ა").
  while (tokens.length > 1 && /^\d/.test(tokens[tokens.length - 1])) {
    tokens.pop();
  }

  tokens = tokens
    .map((t) => STREET_TYPE_CANONICAL[t] ?? t)
    .filter((t) => t.length > 0);

  let joined = tokens.join(" ");
  for (const [re, replacement] of STREET_SPELLING_VARIANTS) {
    joined = joined.replace(re, replacement);
  }
  return joined;
}

/** Canonical full-word street types (values of STREET_TYPE_CANONICAL). */
const STREET_TYPE_VALUE_SET = new Set<string>(
  Object.values(STREET_TYPE_CANONICAL)
);

/** True when the (raw) street name carries an explicit street-type token. */
export function hasStreetType(raw: string | null | undefined): boolean {
  return splitStreetName(raw).type.length > 0;
}

export interface SplitStreetName {
  /** Normalized name without the trailing street-type token. */
  base: string;
  /** Canonical street-type token (e.g. „ქუჩა", „გამზირი") or "" when absent. */
  type: string;
  /** Full normalized name (base + type). */
  norm: string;
}

/**
 * Split a normalized street name into its base name and trailing street-type
 * token. „წერეთლის გამზ." → { base: "წერეთლის", type: "გამზირი" }.
 */
export function splitStreetName(raw: string | null | undefined): SplitStreetName {
  const norm = normalizeStreetForMatch(raw);
  if (!norm) return { base: "", type: "", norm: "" };
  const tokens = norm.split(" ");
  const last = tokens[tokens.length - 1];
  if (tokens.length > 1 && STREET_TYPE_VALUE_SET.has(last)) {
    return { base: tokens.slice(0, -1).join(" "), type: last, norm };
  }
  return { base: norm, type: "", norm };
}

/** One token array is a leading- or trailing-aligned subsequence of the other. */
function tokenPrefixOrSuffix(a: string[], b: string[]): boolean {
  const [short, long] = a.length <= b.length ? [a, b] : [b, a];
  if (short.length === 0) return false;
  const startsAligned = short.every((t, i) => long[i] === t);
  const endOffset = long.length - short.length;
  const endsAligned = short.every((t, i) => long[endOffset + i] === t);
  return startsAligned || endsAligned;
}

/**
 * Type-aware similarity score between a wanted street name and a candidate.
 * Honors the street type: a matching base with the *same* type ranks highest,
 * a matching base with a *conflicting* type is heavily penalized so the correct
 * type (e.g. გამზირი vs ქუჩა) wins even against district-hint bonuses.
 *
 * Returns 0 for a non-match; a strong match is ~1000+.
 */
export function scoreStreetNameMatch(
  want: string | null | undefined,
  candidate: string | null | undefined
): number {
  const w = splitStreetName(want);
  const c = splitStreetName(candidate);
  if (!w.norm || !c.norm) return 0;

  let base = 0;
  if (w.base === c.base) {
    base = 1000;
  } else {
    const wt = w.base.split(" ").filter(Boolean);
    const ct = c.base.split(" ").filter(Boolean);
    if (tokenPrefixOrSuffix(wt, ct)) {
      // Candidate carries extra name tokens (e.g. „აკაკი წერეთლის" vs
      // „წერეთლის"). Penalize by how much longer the candidate is.
      const shorter = Math.min(wt.length, ct.length);
      const longer = Math.max(wt.length, ct.length);
      base = Math.round(820 * (shorter / longer));
    } else if (c.base.startsWith(w.base) || w.base.startsWith(c.base)) {
      // Character-level prefix (handles inflected endings) — proportional.
      const shorter = Math.min(w.base.length, c.base.length);
      const longer = Math.max(w.base.length, c.base.length);
      base = Math.round(560 * (shorter / longer));
    } else {
      return 0;
    }
  }

  if (w.type && c.type) {
    base += w.type === c.type ? 250 : -600;
  } else if (w.type && !c.type) {
    base -= 30;
  } else if (!w.type && c.type) {
    base -= 15;
  }

  return Math.max(0, base);
}

/** Drop the leading token (initial or first name) — used for person-named streets. */
export function streetMatchKeyWithoutLead(raw: string | null | undefined): string {
  const norm = normalizeStreetForMatch(raw);
  if (!norm) return "";
  const tokens = norm.split(" ");
  if (tokens.length <= 1) return norm;
  return tokens.slice(1).join(" ");
}

export function normalizeDistrictKey(raw: string | null | undefined): string {
  if (!raw) return "";
  return nfc(String(raw))
    .toLowerCase()
    .replace(/[-–—_.,\s]+/g, "")
    .trim();
}

interface LookupMaps {
  toSsge: Map<string, string>;
  toMyhome: Map<string, string>;
  toSsgeByDistrict: Map<string, string>;
  toMyhomeByDistrict: Map<string, string>;
}

const SEP = "\u0000";

function districtScopedKey(districtKey: string, nameKey: string): string {
  return `${districtKey}${SEP}${nameKey}`;
}

function buildLookupMaps(entries: StreetCrosswalkEntry[]): LookupMaps {
  const toSsge = new Map<string, string>();
  const toMyhome = new Map<string, string>();
  const toSsgeByDistrict = new Map<string, string>();
  const toMyhomeByDistrict = new Map<string, string>();

  // Insert exact matches first so they win key collisions over fuzzy ones
  // (e.g. an initial-vs-full-name pairing that normalizes to the same key).
  const ordered = [...entries].sort((a, b) => {
    const rank = (c?: StreetCrosswalkConfidence) =>
      c === "manual" ? 0 : c === "exact" ? 1 : 2;
    return rank(a.confidence) - rank(b.confidence);
  });

  for (const entry of ordered) {
    const myhome = entry.myhome?.trim();
    const ssge = entry.ssge?.trim();
    if (!myhome || !ssge) continue;

    const myhomeKey = normalizeStreetForMatch(myhome);
    const ssgeKey = normalizeStreetForMatch(ssge);
    const districtKey = normalizeDistrictKey(entry.district);

    // A name in either spelling should resolve to the canonical target spelling.
    if (myhomeKey && !toSsge.has(myhomeKey)) toSsge.set(myhomeKey, ssge);
    if (ssgeKey && !toSsge.has(ssgeKey)) toSsge.set(ssgeKey, ssge);
    if (ssgeKey && !toMyhome.has(ssgeKey)) toMyhome.set(ssgeKey, myhome);
    if (myhomeKey && !toMyhome.has(myhomeKey)) toMyhome.set(myhomeKey, myhome);

    if (districtKey) {
      if (myhomeKey) {
        toSsgeByDistrict.set(districtScopedKey(districtKey, myhomeKey), ssge);
        toMyhomeByDistrict.set(districtScopedKey(districtKey, myhomeKey), myhome);
      }
      if (ssgeKey) {
        toSsgeByDistrict.set(districtScopedKey(districtKey, ssgeKey), ssge);
        toMyhomeByDistrict.set(districtScopedKey(districtKey, ssgeKey), myhome);
      }
    }
  }

  return { toSsge, toMyhome, toSsgeByDistrict, toMyhomeByDistrict };
}

let cachedMaps: LookupMaps | null = null;

function maps(): LookupMaps {
  if (!cachedMaps) cachedMaps = buildLookupMaps(crosswalk);
  return cachedMaps;
}

/**
 * Resolve a street name to the spelling expected by `target`'s autocomplete.
 * Returns the canonical target-site spelling, or null when the street is not
 * in the crosswalk (caller should fall back to fuzzy querying).
 */
export function resolveStreetForTarget(
  name: string | null | undefined,
  target: StreetTarget,
  opts?: { district?: string | null }
): string | null {
  const key = normalizeStreetForMatch(name);
  if (!key) return null;

  const m = maps();
  const districtKey = normalizeDistrictKey(opts?.district);

  if (districtKey) {
    const scoped =
      target === "ssge"
        ? m.toSsgeByDistrict.get(districtScopedKey(districtKey, key))
        : m.toMyhomeByDistrict.get(districtScopedKey(districtKey, key));
    if (scoped) return scoped;
  }

  const flat = target === "ssge" ? m.toSsge.get(key) : m.toMyhome.get(key);
  return flat ?? null;
}

/** Number of crosswalk entries currently loaded (diagnostics/tests). */
export function streetCrosswalkSize(): number {
  return crosswalk.length;
}
